version: "3.5"
services:
  api:
    container_name: api
    image: api
    build:
      context: ./api/.
    command: -grpc-endpoint racing:9000
    environment:
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
    ports:
        - "${PORT:-8000}:${PORT:-8000}"
  racing:
    container_name: racing
    image: racing
    build:
      context: ./racing/.
    environment:
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
    ports:
        - "${PORT:-9000}:${PORT:-9000}"
