run:
  modules-download-mode: vendor
  issues-exit-code: 1
  tests: true

  timeout: 2m
  skip-dirs-use-default: true
  skip-dirs:
    - proto

linters-settings:
  goimports:
    local-prefixes: git.neds.sh/matty/
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
      
linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gosec
    - goimports
    - revive
    - gofmt
